category: SERVICE
lookups:
  - entityTypes:
      - domain: EXT
        type: SERVICE
    tags:
      matchingMode: ALL
      predicates:
        - tagKeys: ["k8s.pod.name"]
          field: podName
    onMatch:
      onMultipleMatches: RELATE_ALL
    onMiss:
      action: CREATE_UNINSTRUMENTED
      uninstrumented:
        type: SERVICE